### ISSUE TITLE
UnicodeEncodeError

### ISSUE THREAD

**Issue by Sevenyine** [RongRongJi/nonebot_plugin_quote#3]
系统信息：
Windows Server 2019 Datacenter + Python3.10
上传图片如下：
![E2578A4B-A0C7-4116-8977-C6B97B95CB2F](https://user-images.githubusercontent.com/65720409/227777681-a82633fc-5b0b-40fd-898c-cf393b24f4c9.jpeg)
疑似错误字符：【】这个括号
报错如下：

```
03-26 20:58:16 [INFO] nonebot | Event will be handled by Matcher(type='message', module=nonebot_plugin_quote)
03-26 20:58:18 [INFO] nonebot | Matcher(type='message', module=nonebot_plugin_quote) running complete
03-26 20:58:18 [ERROR] nonebot | Running Matcher(type='message', module=nonebot_plugin_quote) failed.
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\NoneBot\GZbot2\bot.py", line 36, in <module>
    nonebot.run(app="__mp_main__:app")
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\__init__.py", line 273, in run
    get_driver().run(*args, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\drivers\fastapi.py", line 187, in run
    uvicorn.run(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\uvicorn\main.py", line 569, in run
    server.run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\uvicorn\server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 603, in run_forever
    self._run_once()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1906, in _run_once
    handle._run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\message.py", line 141, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
> File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\message.py", line 187, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\internal\matcher\matcher.py", line 732, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\internal\matcher\matcher.py", line 707, in simple_run
    await handler(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\dependencies\__init__.py", line 108, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot_plugin_quote\__init__.py", line 104, in record_upload
    json.dump(inverted_index, fc, indent=2, separators=(',',': '), ensure_ascii=False)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\json\__init__.py", line 180, in dump
    fp.write(chunk)
UnicodeEncodeError: 'gbk' codec can't encode character '\xdf' in position 1: illegal multibyte sequence
```

**Comment by RongRongJi** [comment]
你创建的两个json文件是UTF-8编码的吗，如果不是，请先尝试一下修改成UTF-8编码

**Comment by Sevenyine** [comment]
> 你创建的两个json文件是UTF-8编码的吗，如果不是，请先尝试一下修改成UTF-8编码

好的，解决了（）我是傻逼

**Comment by Sevenyine** [comment]
不太对，我这边好了一段时间后又出了问题，没有修改文件，是上传后自己修改的。我保存为utf8后开启bot，上传语录，ctrl+c结束bot，打开文件发现自动变成了GBK编码
图就是打开bot前后使用编辑器查看编码的截图
![2EEDA287-33F0-4DA2-9437-FDFFE2576533](https://user-images.githubusercontent.com/65720409/227895187-256a3596-4532-48db-804a-7c4d62d16cbc.jpeg)

![19BF7D5A-865C-4DF1-90D9-24BE27FFDEE0](https://user-images.githubusercontent.com/65720409/227895170-4b5ec6dc-5983-450a-815c-7e80a2d50fbc.jpeg)
